"""Phase-1 data lake builder — idempotent, free-tier safe, resumable.

Pulls OHLCV from Twelve Data for the configured universe/timeframes and merges into
research/data/<class>/<SYMBOL>_<tf>.csv.gz (dedupe on bar time, UTC, bar-open indexed).
Forming/incomplete last bars are dropped (no look-ahead). Running twice is safe (merge +
dedupe, never double-count). On a missing key or spent daily budget it logs to BLOCKERS.md
and exits 0 — it never fabricates data.

Usage:
  python research/jobs/data_refresh.py --classes all          # full refresh (after NY close)
  python research/jobs/data_refresh.py --classes crypto       # 24/7 instruments only
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                      # research/
sys.path.insert(0, str(ROOT / "src"))
from twelvedata_client import (          # noqa: E402
    TwelveDataClient, MissingKeyError, BudgetExhausted, TwelveDataError,
)

DATA = ROOT / "data"
CFG = yaml.safe_load((ROOT / "config.yaml").read_text("utf-8"))
TF_MIN = {"15min": 15, "1h": 60, "4h": 240, "1day": 1440}


def log_blocker(msg: str):
    line = f"\n### AUTO {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · data_refresh\n{msg}\n"
    try:
        (ROOT / "BLOCKERS.md").open("a", encoding="utf-8").write(line)
    except Exception:
        pass
    print("BLOCKER:", msg, flush=True)


def drop_incomplete(df: pd.DataFrame, interval_min: int, now: pd.Timestamp) -> pd.DataFrame:
    if df.empty:
        return df
    close_time = df["time"] + pd.Timedelta(minutes=interval_min)
    return df[close_time <= now].reset_index(drop=True)


def merge_save(path: Path, fresh: pd.DataFrame) -> pd.DataFrame:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        old = pd.read_csv(path, compression="gzip", parse_dates=["time"])
        both = pd.concat([old, fresh], ignore_index=True)
    else:
        both = fresh
    both = both.drop_duplicates(subset=["time"], keep="last").sort_values("time").reset_index(drop=True)
    both.to_csv(path, index=False, compression="gzip")
    return both


def write_coverage(rows: list[dict]):
    md = ["# DATA_COVERAGE — auto-generated by data_refresh.py",
          f"_Last run: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_\n",
          "| Symbol | tf | bars | first (UTC) | last (UTC) |",
          "|---|---|--:|---|---|"]
    for r in sorted(rows, key=lambda x: (x["symbol"], x["tf"])):
        md.append(f"| {r['symbol']} | {r['tf']} | {r['bars']} | {r['first']} | {r['last']} |")
    (ROOT / "DATA_COVERAGE.md").write_text("\n".join(md) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--classes", default="all", help="CSV of asset classes, or 'all'")
    args = ap.parse_args()

    now = pd.Timestamp.now(tz="UTC").tz_localize(None)
    uni = CFG["universe"]
    want = list(uni) if args.classes == "all" else [c.strip() for c in args.classes.split(",")]
    tfs = CFG["timeframes"]
    rate = CFG.get("rate", {})

    client = None
    try:
        client = TwelveDataClient(DATA / ".td_usage.json",
                                  per_minute=rate.get("per_minute", 8),
                                  per_day=rate.get("per_day", 800))
    except MissingKeyError as e:
        log_blocker(str(e) + "  (Twelve Data pass skipped; yfinance instruments still refreshed.)")

    rows = []; pulled = 0; failed = []
    try:
        for cls in (want if client else []):
            spec = uni.get(cls)
            if not spec:
                print(f"skip unknown class {cls}"); continue
            for sym in spec["symbols"]:
                safe = sym.replace("/", "")
                for tf in tfs:
                    try:
                        df = client.time_series(sym, tf, rate.get("outputsize", 5000))
                        df = drop_incomplete(df, TF_MIN.get(tf, 60), now)
                        merged = merge_save(DATA / cls / f"{safe}_{tf}.csv.gz", df)
                        pulled += 1
                        rows.append(dict(symbol=sym, tf=tf, bars=len(merged),
                                         first=str(merged["time"].iloc[0]) if len(merged) else "-",
                                         last=str(merged["time"].iloc[-1]) if len(merged) else "-"))
                        print(f"ok  {sym:<10} {tf:<5} {len(merged)} bars "
                              f"(budget {client.calls_today()}/{client.per_day})", flush=True)
                    except BudgetExhausted as e:
                        log_blocker(str(e))
                        raise
                    except (TwelveDataError, Exception) as exc:  # noqa: BLE001
                        failed.append(f"{sym} {tf}: {exc}")
                        print(f"ERR {sym} {tf}: {exc}", flush=True)
    except BudgetExhausted:
        pass  # graceful stop; partial progress is saved + idempotent

    # ---- yfinance-sourced instruments (B-003 / D-008): silver, oil — no key, no budget ----
    yfs = CFG.get("yfinance", [])
    if yfs:
        try:
            from yfinance_client import fetch as yf_fetch
            for inst in yfs:
                if args.classes != "all" and inst["asset_class"] not in want:
                    continue
                sym = inst["symbol"]; safe = sym.replace("/", ""); cls = inst["asset_class"]
                for tf in tfs:
                    try:
                        df = yf_fetch(inst["yf"], tf)
                        df = drop_incomplete(df, TF_MIN.get(tf, 60), now)
                        if df.empty:
                            failed.append(f"{sym} {tf}: yfinance empty"); continue
                        merged = merge_save(DATA / cls / f"{safe}_{tf}.csv.gz", df)
                        pulled += 1
                        rows.append(dict(symbol=sym, tf=tf, bars=len(merged),
                                         first=str(merged["time"].iloc[0]) if len(merged) else "-",
                                         last=str(merged["time"].iloc[-1]) if len(merged) else "-"))
                        print(f"ok  {sym:<10} {tf:<5} {len(merged)} bars (yfinance)", flush=True)
                    except Exception as exc:  # noqa: BLE001
                        failed.append(f"{sym} {tf} (yf): {exc}")
                        print(f"ERR {sym} {tf} (yf): {exc}", flush=True)
        except Exception as exc:  # noqa: BLE001
            failed.append(f"yfinance pass failed to import/run: {exc}")

    if rows:
        write_coverage(rows)
    used = f"{client.calls_today()}/{client.per_day}" if client else "0 (no TD key)"
    print(f"\nrefreshed {pulled} series, {len(failed)} failures, {used} TD calls used today.")
    if failed:
        log_blocker("Series that failed to pull (verify symbols / availability on free plan):\n- "
                    + "\n- ".join(failed[:40]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
